apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: p1
value: 1
description: "priority with value 1"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: p2
value: 2
description: "priority with value 2"
