kind: Pod
apiVersion: v1
metadata:
  name: pause
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - kube-node-1
            - kube-node-2
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: Exists
          topologyKey: zone
  containers:
  - name: pause
    image: k8s.gcr.io/pause:3.1
