kind: Pod
apiVersion: v1
metadata:
  name: pause
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - amd64
  containers:
  - name: pause
    image: k8s.gcr.io/pause:3.1