apiVersion: apps/v1
kind: Deployment
metadata:
  name: low-priority
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pause
  template:
    metadata:
      labels:
        app: pause
    spec:
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.2
        resources:
          requests:
            cpu: 3
