kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv4
nodes:
# the control plane node
- role: control-plane
  extraMounts:
  - hostPath: /Users/wei.huang1/projects/k8s-manifests
    containerPath: /mnt
- role: worker
- role: worker
- role: worker
