kind: Pod
apiVersion: v1
metadata:
  name: pause1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - kind-worker3
  containers:
  - name: pause
    image: k8s.gcr.io/pause:3.2
