kind: Pod
apiVersion: v1
metadata:
  name: pause
spec:
  containers:
  - name: pause
    image: k8s.gcr.io/pause:3.2
    volumeMounts:
    - name: volume
      mountPath: /pvc/
  volumes:
  - name: volume
    persistentVolumeClaim:
      claimName: pvc
