apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv3
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 300Mi
  hostPath:
    path: /vol3
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kind-worker3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: retain
