apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pause
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pause
  serviceName: ""
  template:
    metadata:
      labels:
        app: pause
    spec:
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.1