apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pause
  template:
    metadata:
      labels:
        app: pause
    spec:
      schedulerName: binpack
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.2
